services:
  - type: web
    name: lucette-coquette
    runtime: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console cache:clear --env=prod
      php bin/console assets:install --env=prod
    startCommand: |
      php -S 0.0.0.0:$PORT public/index.php
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: lucette-db
          property: connectionString

  - type: pgsql
    name: lucette-db
    databaseName: lucette_coquette
    user: lucette_user